---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceAccountName}}
  namespace: {{.Values.namespace}}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
