apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: cluster-agent
  namespace: acorn
spec:
  autoUpgrade: true
  autoUpgradeInterval: 15s
  profiles:
    - cluster-agent
  deployArgs:
    {{ if .Values.clusterAgentAccountUrl }}
    accountFqdn: {{ .Values.clusterAgentAccountUrl }}
    {{ end }}
    region: {{ .Values.region }}
    {{ if .Values.clusterAgentAccountName }}
    accountName: {{ .Values.clusterAgentAccountName }}
    {{ end }}
    hubUrl: {{ .Values.hubUrl }}
  image: "ghcr.io/acorn-io/hub:{{ .Values.acornTag }}"
  labels:
    - key: "sidecar.istio.io/inject"
      value: "false"
      resourceType: container
  permissions:
    - clusterRules:
        - apiGroups:
            - '*'
          resources:
            - '*'
          verbs:
            - get
            - list
            - watch
            - update
            - patch
            - delete
            - deletecollection
            - create
      serviceName: cluster-agent
  secrets:
    - target: token-cluster-agent
      secret: token-cluster-agent