apiVersion: internal.admin.acorn.io/v1
description: >-
  Hub-generated volume class representing ephemeral volumes not backed by a
  storage class
kind: ClusterVolumeClassInstance
metadata:
  name: ephemeral
---
apiVersion: internal.admin.acorn.io/v1
default: true
description: Hub-generated volume class representing the storage class ebs-retain
kind: ClusterVolumeClassInstance
metadata:
  name: ebs-retain
storageClassName: ebs-retain