apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: acorn-istio-plugin
  namespace: acorn
spec:
  image: ghcr.io/acorn-io/acorn-istio-plugin:prod
  autoUpgrade: true
  autoUpgradeInterval: 15s
  labels:
    - key: "sidecar.istio.io/inject"
      value: "false"
      resourceType: container
  permissions:
    - clusterRules:
        - apiGroups:
            - ""
          resources:
            - namespaces
          verbs:
            - list
            - get
            - patch
            - update
            - watch
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - get
            - create
            - update
        - apiGroups:
            - ""
          resources:
            - pods
          verbs:
            - '*'
        - apiGroups:
            - ""
          resources:
            - pods/ephemeralcontainers
          verbs:
            - patch
            - update
        - apiGroups:
            - security.istio.io
          resources:
            - peerauthentications
            - peerauthentications/status
            - authorizationpolicies
            - authorizationpolicies/status
          verbs:
            - '*'
        - apiGroups:
            - networking.istio.io
          resources:
            - virtualservices
            - virtualservices/status
          verbs:
            - '*'
        - apiGroups:
            - networking.k8s.io
          resources:
            - ingresses
          verbs:
            - list
            - get
            - watch
            - update
        - apiGroups:
            - ""
          resources:
            - services
          verbs:
            - list
            - get
            - watch
        - apiGroups:
            - ""
          resources:
            - nodes
          verbs:
            - list
            - get
      serviceName: istio-plugin-controller