apiVersion: v1
kind: Namespace
metadata:
  name: aws-identity
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: aws-identity
  namespace: kube-system
spec:
  bootstrap: true
  chart: https://ekristen.github.io/helm-charts/amazon-eks-pod-identity-webhook-1.0.3.tgz
  targetNamespace: aws-identity
  valuesContent: |
    replicaCount: 2
    installCRDs: true
    mutatingWebhook:
      failurePolicy: Fail
    config:
      defaultAwsRegion: {{ .Values.region }}
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: "Exists"