apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  chart: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/download/helm-chart-aws-ebs-csi-driver-2.17.0/aws-ebs-csi-driver-2.17.0.tgz
  bootstrap: true
  valuesContent: |
    controller:
      k8sTagClusterId: {{ .Values.clusterName }}
      region: {{ .Values.region }}
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: "Exists"
    installCRDs: true
    node:
      tolerations: {}
      tolerateAllTaints: false
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
    storageClasses:
      - name: ebs-retain
        parameters:
          encrypted: "true"
        reclaimPolicy: Retain
      - name: ebs-ephemeral
        parameters:
          encrypted: "true"
        reclaimPolicy: Delete