{{ if .Values.datadogAgent.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: datadog-agent
  labels:
    release: datadog-agent
    istio-injection: disabled
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-api-key
  namespace: datadog-agent
data:
  api-key: {{ .Values.datadogAgent.apiKey | b64enc }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: datadog-agent
  namespace: kube-system
spec:
  bootstrap: true
  chart: https://github.com/DataDog/helm-charts/releases/download/datadog-3.25.0/datadog-3.25.0.tgz
  targetNamespace: datadog-agent
  valuesContent: |
    datadog:
      apiKeyExistingSecret: datadog-api-key
      site: datadoghq.com
      clusterName: {{ .Values.clusterName }}
      podLabelsAsTags:
        "acorn.io/app-name": acorn_io_app_name
        "acorn.io/job-name": acorn_io_job_name
        "acorn.io/app-namespace": acorn_io_app_namespace
        "acorn.io/container-name": acorn_io_container_name
        "acorn.io/project": acorn_io_project
        "acorn.io/project-name": acorn_io_project_name
        "hub.acorn.io/account-name": hub_acorn_io_account_name
    clusterAgent:
      admissionController:
        enabled: false
      tolerations:
      - key: taints.acorn.io/workload
        operator: "Exists"
    agents:
      tolerations:
      - key: taints.acorn.io/workload
        operator: "Exists"
{{end}}
