{{ if .Values.hubResources }}
apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: cluster-agent
  namespace: acorn
spec:
  autoUpgrade: true
  autoUpgradeInterval: 15s
  profiles:
    - cluster-agent
  deployArgs:
    hubUrl: {{ .Values.clusterAgentAccountUrl }}
  image: ghcr.io/acorn-io/hub:main
  permissions:
    - clusterRules:
        - apiGroups:
            - '*'
          resources:
            - '*'
          verbs:
            - get
            - list
            - watch
            - update
            - patch
            - delete
            - deletecollection
            - create
      serviceName: cluster-agent
  secrets:
    - target: token-cluster-agent
      secret: token-cluster-agent
---
apiVersion: v1
kind: Secret
metadata:
  name: token-cluster-agent
  namespace: acorn
type: secrets.acorn.io/token
data:
  token: {{ .Values.clusterAgentToken | b64enc }}
{{ end }}