{{ if .Values.hubResources }}
apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: cluster-agent
  namespace: acorn
spec:
  autoUpgrade: true
  autoUpgradeInterval: 15s
  profiles:
    - cluster-agent
  deployArgs:
    accountFqdn: {{ .Values.clusterAgentAccountUrl }}
    region: {{ .Values.region }}
    accountName: {{ .Values.clusterAgentAccountName }}
    hubUrl: {{ .Values.hubUrl }}
    accountPlacement: "dev-eng-hub-john-ua"
    projectPlacement: "dev-eng-hub-john-uw-1"
  image: ghcr.io/acorn-io/hub:main
  permissions:
    - clusterRules:
        - apiGroups:
            - '*'
          resources:
            - '*'
          verbs:
            - get
            - list
            - watch
            - update
            - patch
            - delete
            - deletecollection
            - create
      serviceName: cluster-agent
  secrets:
    - target: token-cluster-agent
      secret: token-cluster-agent
---
apiVersion: v1
kind: Secret
metadata:
  name: token-cluster-agent
  namespace: acorn
type: secrets.acorn.io/token
data:
  token: {{ .Values.clusterAgentToken | b64enc }}
---
apiVersion: internal.admin.acorn.io/v1
cpuScaler: 0.25
default: true
description: Default offering
kind: ClusterComputeClassInstance
memory: {}
metadata:
  name: default
---
apiVersion: internal.admin.acorn.io/v1
description: Acorn-generated volume class representing ephemeral volumes not backed by a storage class
kind: ClusterVolumeClassInstance
metadata:
  name: ephemeral
---
apiVersion: internal.admin.acorn.io/v1
default: true
description: Acorn-generated volume class representing the storage class ebs-retain
kind: ClusterVolumeClassInstance
metadata:
  name: ebs-retain
storageClassName: ebs-retain
{{ end }}