{{ if .Values.linkerd }}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: linkerd-control-plane
  namespace: kube-system
spec:
  bootstrap: true
  chart: https://acorn-io.github.io/hub-system-charts/linkerd-control-plane-1.9.6.tgz
  targetNamespace: linkerd
  valuesContent: |
    proxyInjector:
      namespaceSelector:
        matchExpressions:
        - key: config.linkerd.io/admission-webhooks
          operator: NotIn
          values:
          - disabled
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          - kube-system
          - cert-manager
          - aws-identity
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: "Exists"
    identity:
      issuer:
        scheme: "kubernetes.io/tls"
        tls:
          crtPEM: tls.crt
          keyPEM: tls.key
    identityTrustAnchorsPEM: |-{{ .Values.linkerdTrustAnchorsPEM | trim | nindent 6}}
    installNamespace: false
    cniEnabled: true
    enablePodDisruptionBudget: false
    enablePodAntiAffinity: false
    deploymentStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 25%
    tolerations:
    - operator: Exists
      key: taints.acorn.io/workload
    proxy:
      resources:
        cpu:
          request: 100m
        memory:
          limit: 250Mi
          request: 20Mi
    controllerReplicas: 1
    bSideReplicas: 1
    bSideTolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: "Exists"
    controllerResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 500Mi
        request: 250Mi
    destinationResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 500Mi
        request: 250Mi
    identityResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 500Mi
        request: 250Mi
    heartbeatResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 500Mi
        request: 250Mi
    proxyInjectorResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 500Mi
        request: 250Mi
    webhookFailurePolicy: Fail
    spValidatorResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 500Mi
        request: 250Mi
{{ end }}