apiVersion: v1
data:
  account-id: {{ printf "%v" .Values.awsAccountId | b64enc }}
  aws-region: {{ .Values.region | b64enc }}
  vpc-id: {{ .Values.targetVpcId | b64enc }}
kind: Secret
metadata:
  name: context-aws
  namespace: acorn-system
type: acorn.io/context